################################################################
# create_block_design.tcl
# EdgeAI-ZU4EV: Vivado 2020.1 Block Design Automation Script
#
# Board   : ALINX ACU4EV (Xilinx Zynq UltraScale+ XCZU4EV-1SFVC784I)
# Tool    : Vivado 2020.1
# Purpose : Auto-create Block Design with:
#             - Zynq UltraScale+ MPSoC (PS)
#             - AXI DMA (Simple mode)
#             - HLS AI Accelerator IP (myproject_axi — required, no placeholder)
#             - AXI SmartConnect
#             - Clock & Reset logic
#
# Usage   : source create_block_design.tcl
#           (run from Vivado Tcl Console, or vivado -mode batch -source ...)
################################################################

################################################################
# 0. Project Setup
################################################################

set PROJECT_NAME  "EdgeAI_ZU4EV"
set PROJECT_DIR   "./vivado_project"
set BD_NAME       "system"
set PART          "xczu4ev-sfvc784-1-i"
set BOARD_PART    ""   ;# No official board file for ACU4EV — leave blank
set CONSTRAINTS_XDC "./constraints/acu4ev_constraints.xdc"
set SCRIPT_DIR [file dirname [file normalize [info script]]]
set REPO_ROOT [file dirname ${SCRIPT_DIR}]

# HLS IP repository path (generated by hls4ml + Vivado HLS 2020.1 export)
set HLS_IP_REPO   [file normalize [file join ${REPO_ROOT} notebooks hls4ml_prj myproject_prj solution1 impl ip]]

proc property_exists {obj prop_name} {
    expr {[lsearch -exact [list_property $obj] $prop_name] >= 0}
}

proc first_existing_bd_pin {cell patterns} {
    foreach pattern $patterns {
        set pins [get_bd_pins -quiet ${cell}/${pattern}]
        if {[llength $pins] > 0} {
            return [lindex $pins 0]
        }
    }
    return ""
}

proc existing_bd_pins {cell patterns} {
    set matches [list]
    foreach pattern $patterns {
        foreach pin [get_bd_pins -quiet ${cell}/${pattern}] {
            if {[lsearch -exact $matches $pin] < 0} {
                lappend matches $pin
            }
        }
    }
    return $matches
}

proc first_existing_bd_intf_pin {cell patterns} {
    foreach pattern $patterns {
        set pins [get_bd_intf_pins -quiet ${cell}/${pattern}]
        if {[llength $pins] > 0} {
            return [lindex $pins 0]
        }
    }
    return ""
}

proc existing_bd_intf_pins {cell patterns} {
    set matches [list]
    foreach pattern $patterns {
        foreach pin [get_bd_intf_pins -quiet ${cell}/${pattern}] {
            if {[lsearch -exact $matches $pin] < 0} {
                lappend matches $pin
            }
        }
    }
    return $matches
}

proc first_existing_bd_addr_seg {cell patterns} {
    foreach pattern $patterns {
        set segs [get_bd_addr_segs -quiet ${cell}/${pattern}]
        if {[llength $segs] > 0} {
            return [lindex $segs 0]
        }
    }
    return ""
}

proc connect_bd_pins_via_net {net_name pins} {
    if {[llength $pins] < 2} {
        error "connect_bd_pins_via_net requires at least two pins."
    }

    set source_pin [lindex $pins 0]
    set net_obj [lindex [get_bd_nets -quiet -of_objects $source_pin] 0]
    if {$net_obj eq ""} {
        set net_obj [get_bd_nets -quiet $net_name]
        if {[llength $net_obj] == 0} {
            set net_obj [create_bd_net $net_name]
        } else {
            set net_obj [lindex $net_obj 0]
        }
        connect_bd_net -net $net_obj $source_pin
    }

    set target_net_name [get_property NAME $net_obj]
    foreach pin [lrange $pins 1 end] {
        set pin_net [lindex [get_bd_nets -quiet -of_objects $pin] 0]
        if {$pin_net ne "" && [get_property NAME $pin_net] eq $target_net_name} {
            continue
        }
        connect_bd_net -net $net_obj $pin
    }
}

# Create project
create_project ${PROJECT_NAME} ${PROJECT_DIR} -part ${PART} -force

# Set project properties
set_property TARGET_LANGUAGE     Verilog   [current_project]
set_property SIMULATOR_LANGUAGE  Mixed  [current_project]

if {[file exists ${CONSTRAINTS_XDC}]} {
    set constraints_path [file normalize ${CONSTRAINTS_XDC}]
    set existing_constraints [get_files -quiet $constraints_path]
    if {[llength $existing_constraints] == 0} {
        add_files -fileset constrs_1 -norecurse $constraints_path
        puts "INFO: Added board constraints file: ${constraints_path}"
    } else {
        puts "INFO: Reusing existing board constraints file: ${constraints_path}"
    }
} else {
    puts "WARN: Constraints file not found at ${CONSTRAINTS_XDC}"
}

# Add HLS IP repository (comment out if IP not yet generated)
if {[file exists ${HLS_IP_REPO}]} {
    set_property IP_REPO_PATHS [list ${HLS_IP_REPO}] [current_project]
    update_ip_catalog -rebuild
    puts "INFO: HLS IP repository added: ${HLS_IP_REPO}"
} else {
    error "HLS IP repo not found at ${HLS_IP_REPO}. Run HLS export (myproject_axi) first."
}

################################################################
# 1. Create Block Design
################################################################

create_bd_design ${BD_NAME}
update_compile_order -fileset sources_1

################################################################
# 2. Add Zynq UltraScale+ MPSoC (PS)
################################################################

puts "INFO: Adding Zynq UltraScale+ MPSoC..."

set zynq_ps [ create_bd_cell -type ip \
    -vlnv xilinx.com:ip:zynq_ultra_ps_e:3.3 \
    zynq_ultra_ps_e_0 ]

# Apply default board preset (MPSoC) then customise
apply_bd_automation \
    -rule xilinx.com:bd_rule:zynq_ultra_ps_e \
    -config {apply_board_preset "0"} \
    [get_bd_cells zynq_ultra_ps_e_0]

set zynq_ps_cell [get_bd_cells zynq_ultra_ps_e_0]

# ── PS Clock Configuration ──────────────────────────────────────
# PL Clock 0: 200 MHz (factory-aligned PL reference domain)
set ps_config_pairs [list \
    CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {200} \
    CONFIG.PSU__CRL_APB__PL1_REF_CTRL__FREQMHZ {100} \
    CONFIG.PSU__USE__M_AXI_GP0              {0} \
    CONFIG.PSU__USE__S_AXI_GP0              {0} \
    CONFIG.PSU__USE__S_AXI_GP2              {1} \
    CONFIG.PSU__USE__S_AXI_GP3              {0} \
    CONFIG.PSU__USE__S_AXI_HP0_FPD          {1} \
    CONFIG.PSU__USE__S_AXI_HP1_FPD          {0} \
    CONFIG.PSU__USE__S_AXI_HP2_FPD          {0} \
    CONFIG.PSU__USE__S_AXI_HP3_FPD          {0} \
    CONFIG.PSU__HIGH_ADDRESS__ENABLE        {1} \
    CONFIG.PSU__DDR_HIGH_ADDRESS_GUI_ENABLE {1} \
    CONFIG.PSU__MAXIGP0__DATA_WIDTH         {32} \
    CONFIG.PSU__SAXIGP0__DATA_WIDTH         {64} \
    CONFIG.PSU__SAXIGP2__DATA_WIDTH         {64} \
    CONFIG.PSU__USE__IRQ0                   {1} \
]
set ps_config [list]
foreach {prop_name prop_value} $ps_config_pairs {
    if {[property_exists $zynq_ps_cell $prop_name]} {
        lappend ps_config $prop_name $prop_value
    } else {
        puts "WARN: PS property not available on this Vivado/IP version: ${prop_name}"
    }
}
if {[llength $ps_config] > 0} {
    set_property -dict $ps_config $zynq_ps_cell
    set hiaddr [get_property CONFIG.PSU__HIGH_ADDRESS__ENABLE $zynq_ps_cell]
    puts "INFO: PS CONFIG.PSU__HIGH_ADDRESS__ENABLE = ${hiaddr}"
}

# ── Enable DDR ───────────────────────────────────────────────────
# PS DDR4: 4GB 64-bit (configured by board, keep defaults)
# PL DDR4: NOT directly accessible via PS — handled via XDMA or soft MIG
# For this design, DMA uses PS HP0 → PS DDR4 path.
set_property -dict [list \
    CONFIG.PSU__DDRC__ENABLE {1} \
] $zynq_ps_cell

################################################################
# 3. PL reference clock + Processor System Reset (factory-aligned)
#    ref_fact: MMCM 200MHz domain feeds DMA aclk + proc_sys_reset slowest_sync_clk;
#    dcm_locked <- MMCM locked; ext_reset_in <- pl_resetn0; aux_reset_in <- 1.
################################################################

puts "INFO: Adding PL reference clock (clk_wiz) + proc_sys_reset..."

set BYPASS_CLK_WIZ 0
if {[info exists ::env(BYPASS_CLK_WIZ)] && $::env(BYPASS_CLK_WIZ) ne "" && $::env(BYPASS_CLK_WIZ) ne "0"} {
    set BYPASS_CLK_WIZ 1
}

if {!$BYPASS_CLK_WIZ} {
    set pl_ref_clk [create_bd_cell -type ip \
        -vlnv xilinx.com:ip:clk_wiz:6.0 \
        pl_ref_clk]
    # clk_wiz configured after pl_clk0 is connected (FREQ_HZ must match exactly).
} else {
    puts "INFO: BYPASS_CLK_WIZ=1 — skip clk_wiz, use PS pl_clk0 directly"
}

set rst_pl [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:proc_sys_reset:5.0 \
    proc_sys_reset_pl]

# HLS input stream is 16-bit; output may be 16- or 32-bit (OUTPUT_AXIS_BITS env).
set HLS_AXIS_TDATA_BYTES 2
set HLS_AXIS_TDATA_WIDTH [expr {${HLS_AXIS_TDATA_BYTES} * 8}]
set HLS_OUTPUT_AXIS_BYTES 2
if {[info exists ::env(HLS_OUTPUT_AXIS_BITS)] && $::env(HLS_OUTPUT_AXIS_BITS) ne ""} {
    set obits $::env(HLS_OUTPUT_AXIS_BITS)
    if {$obits eq "32"} {
        set HLS_OUTPUT_AXIS_BYTES 4
    }
}
set HLS_OUTPUT_AXIS_WIDTH [expr {${HLS_OUTPUT_AXIS_BYTES} * 8}]

################################################################
# 4. AXI DMA — Simple Mode (64-bit mem, 16-bit AXI-Stream)
################################################################

puts "INFO: Adding AXI DMA..."

set axi_dma [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_dma:7.1 \
    axi_dma_0]

# S2MM AXIS width: 32 when HLS outputs 32-bit native or via axis_dwidth_converter.
set S2MM_AXIS_TDATA_WIDTH 32
if {$HLS_OUTPUT_AXIS_BYTES eq 4} {
    set S2MM_AXIS_TDATA_WIDTH ${HLS_OUTPUT_AXIS_WIDTH}
}

# M_AXI stays 32-bit (DMA native). SmartConnect MI / HP0 are 64-bit — insert
# axi_dwidth_converter on S2MM write path to avoid sparse DRAM (hole pattern).
set DMA_M_AXI_DATA_WIDTH 32

set_property -dict [list \
    CONFIG.c_include_sg          {0} \
    CONFIG.c_sg_include_stscntrl_strm {0} \
    CONFIG.c_m_axi_mm2s_data_width ${DMA_M_AXI_DATA_WIDTH} \
    CONFIG.c_m_axis_mm2s_tdata_width ${HLS_AXIS_TDATA_WIDTH} \
    CONFIG.c_m_axi_s2mm_data_width ${DMA_M_AXI_DATA_WIDTH} \
    CONFIG.c_s_axis_s2mm_tdata_width ${S2MM_AXIS_TDATA_WIDTH} \
    CONFIG.c_include_mm2s_dre    {1} \
    CONFIG.c_include_s2mm_dre    {1} \
    CONFIG.c_mm2s_burst_size     {256} \
    CONFIG.c_s2mm_burst_size     {256} \
    CONFIG.c_include_mm2s        {1} \
    CONFIG.c_include_s2mm        {1} \
    CONFIG.c_addr_width          {32} \
] [get_bd_cells axi_dma_0]

################################################################
# 5. AXI Interconnect — PS ↔ DMA / GPIO / UART (factory ps8_0_axi_periph pattern)
#    ref_fact: HPM0_LPD -> axi_interconnect; ARESETN<-interconnect_aresetn;
#    Mxx/S00_ARESETN + DMA axi_resetn <- peripheral_aresetn.
################################################################

puts "INFO: Adding AXI Interconnect (control path, factory-aligned)..."

set ps_axi_periph [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_interconnect:2.1 \
    ps_axi_periph]

set_property -dict [list \
    CONFIG.NUM_SI {1} \
    CONFIG.NUM_MI {4} \
] [get_bd_cells ps_axi_periph]

################################################################
# 5A. AXI GPIO / UARTLite — Board Debug I/O
################################################################

puts "INFO: Adding AXI GPIO / UARTLite debug peripherals..."

set axi_gpio_led [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_gpio:2.0 \
    axi_gpio_led]
set_property -dict [list \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO_WIDTH  {1} \
] [get_bd_cells axi_gpio_led]

set axi_gpio_debug [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_gpio:2.0 \
    axi_gpio_debug]
set_property -dict [list \
    CONFIG.C_ALL_OUTPUTS {1} \
    CONFIG.C_GPIO_WIDTH  {4} \
] [get_bd_cells axi_gpio_debug]

set axi_uart_dbg [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_uartlite:2.0 \
    axi_uart_dbg]

################################################################
# 6. AXI SmartConnect — DMA ↔ PS HP0 (Data path)
################################################################

puts "INFO: Adding AXI SmartConnect (data path)..."

set sc_data [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:smartconnect:1.0 \
    smartconnect_data]

# 2 masters (DMA MM2S + S2MM), 1 slave (PS HP0)
set_property -dict [list \
    CONFIG.NUM_SI {2} \
    CONFIG.NUM_MI {1} \
] [get_bd_cells smartconnect_data]

################################################################
# 7. HLS AI Accelerator IP (myproject_axi: single AXIS in/out, ap_ctrl_none)
#    Required — abort if missing (no FIFO placeholder).
################################################################

puts "INFO: Adding HLS AI Accelerator IP..."

set hls_ip_vlnv ""

# Only accept the single-stream wrapper IP; legacy multi-AXIS myproject is rejected.
set ip_list [get_ipdefs -filter {VLNV =~ *myproject_axi*}]
if {[llength $ip_list] == 0} {
    error "myproject_axi not found in IP catalog at ${HLS_IP_REPO}.\
 Run: vivado_hls -f build_prj.tcl with set_top myproject_axi, export=1, then re-run this script."
}

set hls_ip_vlnv [lindex $ip_list 0]
set hls_accel [create_bd_cell -type ip \
    -vlnv ${hls_ip_vlnv} \
    cifar10_accel_0]
puts "INFO: HLS IP instantiated: ${hls_ip_vlnv}"
catch { upgrade_ip [get_ips cifar10_accel_0] }
catch { report_ip_status [get_ips cifar10_accel_0] }

################################################################
# 7A. External Board Ports
################################################################

puts "INFO: Creating external debug ports..."

set port_pl_led1       [create_bd_port -dir O pl_led1]
set port_pl_status_gpio [create_bd_port -dir O -from 3 -to 0 pl_status_gpio]
set port_pl_uart_rxd   [create_bd_port -dir I pl_uart_rxd]
set port_pl_uart_txd   [create_bd_port -dir O pl_uart_txd]

connect_bd_net \
    [get_bd_pins axi_gpio_led/gpio_io_o] \
    [get_bd_ports pl_led1]

connect_bd_net \
    [get_bd_pins axi_gpio_debug/gpio_io_o] \
    [get_bd_ports pl_status_gpio]

connect_bd_net \
    [get_bd_pins axi_uart_dbg/rx] \
    [get_bd_ports pl_uart_rxd]

connect_bd_net \
    [get_bd_pins axi_uart_dbg/tx] \
    [get_bd_ports pl_uart_txd]

################################################################
# 8. Clock Connections
################################################################

puts "INFO: Connecting clocks..."

set ps_clk0_pin [first_existing_bd_pin zynq_ultra_ps_e_0 [list pl_clk0]]
set ps_resetn_pin [first_existing_bd_pin zynq_ultra_ps_e_0 [list pl_resetn0 pl_resetn1]]

if {$BYPASS_CLK_WIZ} {
    set pl_dma_clk_pin $ps_clk0_pin
    puts "INFO: pl_dma_clk = pl_clk0 (direct)"
} else {
    set pl_dma_clk_pin [get_bd_pins pl_ref_clk/clk_out1]
}

if {$ps_clk0_pin eq ""} {
    error "Could not find a usable PS clock pin (expected pl_clk0 or equivalent)."
}
if {$ps_resetn_pin eq ""} {
    error "Could not find a usable PS reset pin (expected pl_resetn0 or equivalent)."
}

# clk_wiz input from PS PL clock (match FREQ_HZ exactly for BD validation)
if {!$BYPASS_CLK_WIZ} {
    connect_bd_net $ps_clk0_pin [get_bd_pins pl_ref_clk/clk_in1]
    set pl_freq_hz [get_property CONFIG.FREQ_HZ $ps_clk0_pin]
    if {$pl_freq_hz eq ""} {
        set pl_freq_hz [get_property FREQ_HZ $ps_clk0_pin]
    }
    if {$pl_freq_hz eq ""} {
        set pl_freq_hz 200000000
    }
    set pl_freq_mhz [format %.6f [expr {$pl_freq_hz / 1000000.0}]]
    set pl_period_ns [format %.3f [expr {1000.0 / $pl_freq_mhz}]]
    set_property -dict [list \
        CONFIG.PRIM_IN_FREQ $pl_freq_mhz \
        CONFIG.PRIM_SOURCE {No_buffer} \
        CONFIG.CLKOUT1_REQUESTED_OUT_FREQ $pl_freq_mhz \
        CONFIG.NUM_OUT_CLKS {1} \
        CONFIG.USE_RESET {false} \
        CONFIG.MMCM_CLKFBOUT_MULT_F {1.000} \
        CONFIG.MMCM_CLKOUT0_DIVIDE_F {1.000} \
        CONFIG.MMCM_CLKIN1_PERIOD $pl_period_ns \
    ] [get_bd_cells pl_ref_clk]
    puts "INFO: pl_ref_clk configured: in=${pl_freq_mhz} MHz out=${pl_freq_mhz} MHz (factory 1:1 buffer)"
}

set accel_clock_pins [existing_bd_pins cifar10_accel_0 [list aclk ap_clk s_axis_aclk m_axis_aclk]]
set accel_reset_pins [existing_bd_pins cifar10_accel_0 [list aresetn ap_rst_n s_axis_aresetn m_axis_aresetn]]

# proc_sys_reset on same clock net as DMA (factory pattern)
connect_bd_net \
    $pl_dma_clk_pin \
    [get_bd_pins proc_sys_reset_pl/slowest_sync_clk]

connect_bd_net \
    $ps_resetn_pin \
    [get_bd_pins proc_sys_reset_pl/ext_reset_in]

if {$BYPASS_CLK_WIZ} {
    puts "INFO: BYPASS_CLK_WIZ=1 — dcm_locked left unconnected (factory ref_fact pattern)"
} else {
    connect_bd_net \
        [get_bd_pins pl_ref_clk/locked] \
        [get_bd_pins proc_sys_reset_pl/dcm_locked]
}

# factory ref_fact leaves aux_reset_in unconnected on rst_ps8_0_200M

# DMA + data path on pl_ref_clk 200MHz domain
connect_bd_net \
    $pl_dma_clk_pin \
    [get_bd_pins axi_dma_0/m_axi_mm2s_aclk] \
    [get_bd_pins axi_dma_0/m_axi_s2mm_aclk] \
    [get_bd_pins axi_dma_0/s_axi_lite_aclk] \
    [get_bd_pins smartconnect_data/aclk] \
    [get_bd_pins ps_axi_periph/ACLK] \
    [get_bd_pins ps_axi_periph/S00_ACLK] \
    [get_bd_pins ps_axi_periph/M00_ACLK] \
    [get_bd_pins ps_axi_periph/M01_ACLK] \
    [get_bd_pins ps_axi_periph/M02_ACLK] \
    [get_bd_pins ps_axi_periph/M03_ACLK] \
    [get_bd_pins axi_gpio_led/s_axi_aclk] \
    [get_bd_pins axi_gpio_debug/s_axi_aclk] \
    [get_bd_pins axi_uart_dbg/s_axi_aclk]
set ps_ctrl_aclk_pins [existing_bd_pins zynq_ultra_ps_e_0 [list \
    maxihpm0_fpd_aclk \
    maxihpm0_lpd_aclk \
    maxihpm1_fpd_aclk \
    maxihpm1_lpd_aclk \
]]
if {[llength $ps_ctrl_aclk_pins] > 0} {
    connect_bd_pins_via_net ps_ctrl_aclk_net [linsert $ps_ctrl_aclk_pins 0 $pl_dma_clk_pin]
}

# PS AXI data interface clocks
set ps_data_aclk_pins [existing_bd_pins zynq_ultra_ps_e_0 [list \
    saxihp0_fpd_aclk \
    saxihp1_fpd_aclk \
    saxihpc0_fpd_aclk \
    saxihpc1_fpd_aclk \
    saxigp2_fpd_aclk \
    saxigp3_fpd_aclk \
    saxigp2_aclk \
    saxigp3_aclk \
]]
if {[llength $ps_data_aclk_pins] > 0} {
    connect_bd_pins_via_net ps_data_aclk_net [linsert $ps_data_aclk_pins 0 $pl_dma_clk_pin]
}

# HLS accelerator: pl_dma_clk
if {[llength $accel_clock_pins] == 0} {
    error "Could not find a clock pin on cifar10_accel_0."
}
connect_bd_pins_via_net accel_clk_net [linsert $accel_clock_pins 0 $pl_dma_clk_pin]

# Note: axi_dma 7.1 has no separate m_axis_mm2s_aclk / s_axis_s2mm_aclk pins.
# M_AXIS_MM2S is clocked by m_axi_mm2s_aclk; S_AXIS_S2MM by m_axi_s2mm_aclk
# (both already tied to pl_ref_clk above).

################################################################
# 9. Reset Connections
################################################################

puts "INFO: Connecting resets (factory ref_fact split: interconnect vs peripheral)..."

connect_bd_net \
    [get_bd_pins proc_sys_reset_pl/interconnect_aresetn] \
    [get_bd_pins ps_axi_periph/ARESETN]

connect_bd_net \
    [get_bd_pins proc_sys_reset_pl/peripheral_aresetn] \
    [get_bd_pins ps_axi_periph/S00_ARESETN] \
    [get_bd_pins ps_axi_periph/M00_ARESETN] \
    [get_bd_pins ps_axi_periph/M01_ARESETN] \
    [get_bd_pins ps_axi_periph/M02_ARESETN] \
    [get_bd_pins ps_axi_periph/M03_ARESETN] \
    [get_bd_pins smartconnect_data/aresetn] \
    [get_bd_pins axi_dma_0/axi_resetn]

if {[llength $accel_reset_pins] == 0} {
    error "Could not find a reset pin on cifar10_accel_0."
}
connect_bd_pins_via_net accel_resetn_net [linsert $accel_reset_pins 0 [get_bd_pins proc_sys_reset_pl/peripheral_aresetn]]

connect_bd_net \
    [get_bd_pins proc_sys_reset_pl/peripheral_aresetn] \
    [get_bd_pins axi_gpio_led/s_axi_aresetn] \
    [get_bd_pins axi_gpio_debug/s_axi_aresetn] \
    [get_bd_pins axi_uart_dbg/s_axi_aresetn]

################################################################
# 10. AXI Interface Connections
################################################################

puts "INFO: Connecting AXI interfaces..."

# ── Control Path: PS HPM0 -> AXI Interconnect -> DMA / GPIO / UART (factory) ──
set ps_hpm_master [first_existing_bd_intf_pin zynq_ultra_ps_e_0 [list \
    M_AXI_HPM0_LPD \
    M_AXI_HPM0_FPD \
]]
if {$ps_hpm_master eq ""} {
    error "Could not find PS HPM0 master (expected M_AXI_HPM0_LPD or M_AXI_HPM0_FPD)"
}
puts "INFO: PS control master: ${ps_hpm_master}"

connect_bd_intf_net \
    $ps_hpm_master \
    [get_bd_intf_pins ps_axi_periph/S00_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins ps_axi_periph/M00_AXI] \
    [get_bd_intf_pins axi_dma_0/S_AXI_LITE]

connect_bd_intf_net \
    [get_bd_intf_pins ps_axi_periph/M01_AXI] \
    [get_bd_intf_pins axi_gpio_led/S_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins ps_axi_periph/M02_AXI] \
    [get_bd_intf_pins axi_gpio_debug/S_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins ps_axi_periph/M03_AXI] \
    [get_bd_intf_pins axi_uart_dbg/S_AXI]

# ── Data Path: DMA → SmartConnect_data → PS HP0 (preferred over SAXIGP2)
set ps_hp_slave_intf [first_existing_bd_intf_pin zynq_ultra_ps_e_0 [list \
    S_AXI_HP0_FPD \
    S_AXI_GP2 \
]]
if {$ps_hp_slave_intf eq ""} {
    set available_ps_slave_intfs [existing_bd_intf_pins zynq_ultra_ps_e_0 [list S_AXI*]]
    error "Could not find a PS slave AXI interface for DMA. Available PS slave interfaces: [join $available_ps_slave_intfs {, }]"
}
puts "INFO: Using PS slave AXI interface for DMA path: ${ps_hp_slave_intf}"

# S2MM write: 32-bit DMA -> 64-bit upsizer -> SmartConnect (fixes DRAM hole pattern)
set axi_dwidth_s2mm [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:axi_dwidth_converter:2.1 \
    axi_dwidth_s2mm]
set_property -dict [list \
    CONFIG.SI_DATA_WIDTH {32} \
    CONFIG.MI_DATA_WIDTH {64} \
] [get_bd_cells axi_dwidth_s2mm]
connect_bd_net $pl_dma_clk_pin [get_bd_pins axi_dwidth_s2mm/aclk]
connect_bd_net \
    [get_bd_pins proc_sys_reset_pl/peripheral_aresetn] \
    [get_bd_pins axi_dwidth_s2mm/aresetn]

connect_bd_intf_net \
    [get_bd_intf_pins axi_dma_0/M_AXI_MM2S] \
    [get_bd_intf_pins smartconnect_data/S00_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins axi_dma_0/M_AXI_S2MM] \
    [get_bd_intf_pins axi_dwidth_s2mm/S_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins axi_dwidth_s2mm/M_AXI] \
    [get_bd_intf_pins smartconnect_data/S01_AXI]

connect_bd_intf_net \
    [get_bd_intf_pins smartconnect_data/M00_AXI] \
    $ps_hp_slave_intf
puts "INFO: S2MM path uses axi_dwidth_s2mm 32->64 before SmartConnect/HP0"

# ── AXI4-Stream: DMA MM2S → HLS Accel input_stream ──
# Prefer explicit myproject_axi stream interface names.
set accel_in_intf [first_existing_bd_intf_pin cifar10_accel_0 [list \
    input_stream \
    S_AXIS \
    S_AXIS_DATA \
    input_* \
]]
set accel_out_intf [first_existing_bd_intf_pin cifar10_accel_0 [list \
    output_stream \
    M_AXIS \
    M_AXIS_RESULT \
    output_* \
]]

if {$accel_in_intf eq "" || $accel_out_intf eq ""} {
    set available_accel_intfs [get_bd_intf_pins -quiet cifar10_accel_0/*]
    error "Could not find AXI-Stream interfaces on cifar10_accel_0. Available: [join $available_accel_intfs {, }]"
}

puts "INFO: HLS stream in  = ${accel_in_intf}"
puts "INFO: HLS stream out = ${accel_out_intf}"

set DMA_STREAM_LOOPBACK 0
if {[info exists ::env(DMA_STREAM_LOOPBACK)] && $::env(DMA_STREAM_LOOPBACK) ne "" && $::env(DMA_STREAM_LOOPBACK) ne "0"} {
    set DMA_STREAM_LOOPBACK 1
}

if {$DMA_STREAM_LOOPBACK} {
    puts "INFO: DMA_STREAM_LOOPBACK=1 — MM2S -> axis_data_fifo -> S2MM (HLS axis idle)"

    set lb_tbytes [expr {${HLS_AXIS_TDATA_WIDTH} / 8}]
    set dma_lb_fifo [create_bd_cell -type ip \
        -vlnv xilinx.com:ip:axis_data_fifo:2.0 \
        dma_lb_fifo]
    set_property -dict [list \
        CONFIG.TDATA_NUM_BYTES ${lb_tbytes} \
        CONFIG.FIFO_DEPTH {512} \
        CONFIG.HAS_TLAST {1} \
        CONFIG.HAS_TKEEP {1} \
        CONFIG.HAS_TSTRB {0} \
    ] [get_bd_cells dma_lb_fifo]

    connect_bd_intf_net \
        [get_bd_intf_pins axi_dma_0/M_AXIS_MM2S] \
        [get_bd_intf_pins dma_lb_fifo/S_AXIS]

    connect_bd_intf_net \
        [get_bd_intf_pins dma_lb_fifo/M_AXIS] \
        [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM]

    connect_bd_net $pl_dma_clk_pin [get_bd_pins dma_lb_fifo/s_axis_aclk]
    connect_bd_net \
        [get_bd_pins proc_sys_reset_pl/peripheral_aresetn] \
        [get_bd_pins dma_lb_fifo/s_axis_aresetn]

    # HLS off datapath: tvalid=0 in, tready=1 out (xlconstant — no axis_constant IP in 2020.1)
    set xl_hls_tv0 [create_bd_cell -type ip \
        -vlnv xilinx.com:ip:xlconstant:1.1 \
        xlconst_hls_tvalid0]
    set_property -dict [list CONFIG.CONST_VAL {0} CONFIG.CONST_WIDTH {1}] \
        [get_bd_cells xlconst_hls_tvalid0]
    set xl_hls_tr1 [create_bd_cell -type ip \
        -vlnv xilinx.com:ip:xlconstant:1.1 \
        xlconst_hls_tready1]
    set_property -dict [list CONFIG.CONST_VAL {1} CONFIG.CONST_WIDTH {1}] \
        [get_bd_cells xlconst_hls_tready1]

    set hls_tvalid_pin [get_bd_pins -quiet cifar10_accel_0/input_stream_TVALID]
    set hls_tready_pin [get_bd_pins -quiet cifar10_accel_0/output_stream_TREADY]
    if {$hls_tvalid_pin ne ""} {
        connect_bd_net [get_bd_pins xlconst_hls_tvalid0/dout] $hls_tvalid_pin
    } else {
        puts "WARN: input_stream_TVALID pin not exposed — HLS input may float"
    }
    if {$hls_tready_pin ne ""} {
        connect_bd_net [get_bd_pins xlconst_hls_tready1/dout] $hls_tready_pin
    } else {
        puts "WARN: output_stream_TREADY pin not exposed — HLS output may backpressure"
    }
} else {
    connect_bd_intf_net \
        [get_bd_intf_pins axi_dma_0/M_AXIS_MM2S] \
        $accel_in_intf

    if {$HLS_OUTPUT_AXIS_BYTES eq 4} {
        connect_bd_intf_net \
            $accel_out_intf \
            [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM]
        puts "INFO: HLS ${HLS_OUTPUT_AXIS_WIDTH}-bit output -> DMA S2MM (no dwidth converter)"
    } else {
        # ── HLS 16-bit stream → 32-bit before S2MM ──
        set axis_dw_s2mm [create_bd_cell -type ip \
            -vlnv xilinx.com:ip:axis_dwidth_converter:1.1 \
            axis_dw_s2mm]
        set_property -dict [list \
            CONFIG.S_TDATA_NUM_BYTES {2} \
            CONFIG.M_TDATA_NUM_BYTES {4} \
        ] [get_bd_cells axis_dw_s2mm]

        connect_bd_net $pl_dma_clk_pin [get_bd_pins axis_dw_s2mm/aclk]
        connect_bd_net \
            [get_bd_pins proc_sys_reset_pl/peripheral_aresetn] \
            [get_bd_pins axis_dw_s2mm/aresetn]

        connect_bd_intf_net $accel_out_intf [get_bd_intf_pins axis_dw_s2mm/S_AXIS]
        connect_bd_intf_net \
            [get_bd_intf_pins axis_dw_s2mm/M_AXIS] \
            [get_bd_intf_pins axi_dma_0/S_AXIS_S2MM]
        puts "INFO: axis_dwidth_converter 16->32 on HLS output -> DMA S2MM"
    }
}

# ── DMA Interrupts → PS IRQ (MM2S + S2MM) ──
set irq_concat [create_bd_cell -type ip \
    -vlnv xilinx.com:ip:xlconcat:2.1 \
    irq_concat_dma]

set_property -dict [list CONFIG.NUM_PORTS {2}] [get_bd_cells irq_concat_dma]

connect_bd_net \
    [get_bd_pins axi_dma_0/mm2s_introut] \
    [get_bd_pins irq_concat_dma/In0]

connect_bd_net \
    [get_bd_pins axi_dma_0/s2mm_introut] \
    [get_bd_pins irq_concat_dma/In1]

connect_bd_net \
    [get_bd_pins irq_concat_dma/dout] \
    [get_bd_pins zynq_ultra_ps_e_0/pl_ps_irq0]

puts "INFO: DMA IRQ map: mm2s_introut -> irq_concat In0, s2mm_introut -> irq_concat In1 -> pl_ps_irq0"

################################################################
# 11. Address Editor (Manual assignment for reproducibility)
################################################################

puts "INFO: Assigning addresses..."

# Control registers in HPM0_LPD aperture (factory ref_fact uses 0x8004_0000 band)
# Valid master aperture: 0x8000_0000 [ 512M ] — 0xA000_0000 is OUT OF RANGE.
assign_bd_address \
    [get_bd_addr_segs axi_dma_0/S_AXI_LITE/Reg] \
    -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] \
    -offset 0x80040000 \
    -range 64K

assign_bd_address \
    [get_bd_addr_segs axi_gpio_led/S_AXI/Reg] \
    -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] \
    -offset 0x80090000 \
    -range 64K

assign_bd_address \
    [get_bd_addr_segs axi_gpio_debug/S_AXI/Reg] \
    -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] \
    -offset 0x80080000 \
    -range 64K

assign_bd_address \
    [get_bd_addr_segs axi_uart_dbg/S_AXI/Reg] \
    -target_address_space [get_bd_addr_spaces zynq_ultra_ps_e_0/Data] \
    -offset 0x800A0000 \
    -range 64K

################################################################
# 12. Validate & Save (first pass — populates DMA address spaces)
################################################################

puts "INFO: Validating Block Design (pass 1 — populates DMA address spaces)..."
validate_bd_design

# DMA master address spaces only exist AFTER validate_bd_design.
# Assign HP0 DDR segments to both MM2S and S2MM address spaces.
puts "INFO: Assigning PS DDR to DMA master address spaces..."
foreach dma_space_name {Data_MM2S Data_S2MM} {
    set dma_space [get_bd_addr_spaces -quiet axi_dma_0/${dma_space_name}]
    if {$dma_space eq ""} {
        set dma_space [get_bd_addr_spaces -quiet /axi_dma_0/${dma_space_name}]
    }
    if {$dma_space eq ""} {
        puts "ERROR: Address space axi_dma_0/${dma_space_name} not found even after validate!"
        continue
    }
    foreach intf_name {S_AXI_HP0_FPD SAXIGP2} {
        foreach seg_name {HP0_DDR_LOW HP0_LPS_OCM} {
            set seg [get_bd_addr_segs -quiet zynq_ultra_ps_e_0/${intf_name}/${seg_name}]
            if {$seg ne ""} {
                assign_bd_address $seg -target_address_space $dma_space
                puts "INFO: Assigned ${intf_name}/${seg_name} -> ${dma_space_name}"
            }
        }
    }
}

puts "INFO: Validating Block Design (pass 2 — after DMA address assignment)..."
validate_bd_design

puts "INFO: Saving Block Design..."
save_bd_design

################################################################
# 13. Generate HDL Wrapper
################################################################

puts "INFO: Generating HDL Wrapper..."
make_wrapper -files [get_files system.bd] -top
add_files -norecurse \
    ${PROJECT_DIR}/${PROJECT_NAME}.srcs/sources_1/bd/system/hdl/system_wrapper.v

set_property top system_wrapper [current_fileset]
update_compile_order -fileset sources_1

################################################################
# 14. Generate Output Products & Synthesis Run Setup
################################################################

puts "INFO: Generating output products..."
generate_target all [get_files system.bd]

# Create synthesis run (do not launch yet — add XDC first)
set synth_run [get_runs -quiet synth_1]
if {[llength $synth_run] == 0} {
    create_run synth_1 -flow {Vivado Synthesis 2020}
    set synth_run [get_runs synth_1]
} else {
    puts "INFO: Reusing existing synthesis run: synth_1"
}

set impl_run [get_runs -quiet impl_1]
if {[llength $impl_run] == 0} {
    create_run impl_1 -flow {Vivado Implementation 2020} -parent $synth_run
    set impl_run [get_runs impl_1]
} else {
    puts "INFO: Reusing existing implementation run: impl_1"
}
current_run $synth_run

puts ""
puts "================================================================"
puts "  Block Design created successfully!"
puts "  Project : ${PROJECT_DIR}"
puts "  BD Name : ${BD_NAME}"
puts ""
puts "  HLS IP loaded : ${hls_ip_vlnv}"
puts "  Stream width  : ${HLS_AXIS_TDATA_WIDTH}-bit (matches myproject_axi)"
puts ""
puts "  Next steps:"
puts "  1. One-shot synth+impl+bitstream:"
puts "       vivado -mode batch -source tcl/run_impl_and_bitstream.tcl"
puts "  2. Or manually: launch_runs synth_1; launch_runs impl_1 -to_step write_bitstream"
puts "  3. Export package: source tcl/export_bitstream.tcl (also run by step 2 script)"
puts "================================================================"
