################################################################
# export_bitstream.tcl
# EdgeAI-ZU4EV — Export bitstream + HWH for PYNQ deployment
#
# Run after successful Vivado 2020.1 implementation:
#   Tcl Console → source tcl/export_bitstream.tcl
#
# Outputs (in ./deploy/):
#   cifar10_accel.bit   — FPGA bitstream
#   cifar10_accel.hwh   — Hardware Hand-off file (PYNQ overlay descriptor)
#   cifar10_accel.xsa   — Xilinx Support Archive (for PetaLinux BSP)
################################################################

set DEPLOY_DIR  "./deploy"
set PROJECT_DIR "./vivado_project"
set BD_NAME     "system"
set DESIGN_NAME "cifar10_accel"
set IMPL_RUN    "impl_1"

# Create deploy directory
file mkdir ${DEPLOY_DIR}

# ── Step 1: Check implementation is complete ─────────────────
set run_status [get_property STATUS [get_runs ${IMPL_RUN}]]
puts "INFO: ${IMPL_RUN} status: ${run_status}"

if {$run_status ne "write_bitstream Complete!"} {
    puts "WARN: Implementation may not be complete. Status: ${run_status}"
    puts "      Attempting to write bitstream anyway..."
    open_run ${IMPL_RUN}
    write_bitstream -force "${DEPLOY_DIR}/${DESIGN_NAME}.bit"
} else {
    # Copy bitstream from Vivado run directory
    set bit_src [glob -nocomplain "${PROJECT_DIR}/*.runs/${IMPL_RUN}/*.bit"]
    if {[llength $bit_src] == 0} {
        set bit_src [glob -nocomplain "${PROJECT_DIR}/*.runs/${IMPL_RUN}/system_wrapper.bit"]
    }
    if {[llength $bit_src] > 0} {
        file copy -force [lindex $bit_src 0] "${DEPLOY_DIR}/${DESIGN_NAME}.bit"
        puts "INFO: Bitstream copied to ${DEPLOY_DIR}/${DESIGN_NAME}.bit"
    } else {
        puts "WARN: Bitstream not found. Check ${IMPL_RUN} directory."
    }
}

# ── Step 2: Export Hardware Hand-off File (HWH) ─────────────
# HWH file is needed by PYNQ to parse IP addresses and interrupt mappings
set hwh_src [glob -nocomplain \
    "${PROJECT_DIR}/*.srcs/sources_1/bd/${BD_NAME}/hw_handoff/${BD_NAME}.hwh"]

if {[llength $hwh_src] > 0} {
    file copy -force [lindex $hwh_src 0] "${DEPLOY_DIR}/${DESIGN_NAME}.hwh"
    puts "INFO: HWH file copied to ${DEPLOY_DIR}/${DESIGN_NAME}.hwh"
} else {
    puts "WARN: HWH file not found. Trying to generate..."
    write_hw_platform -fixed -force \
        -include_bit \
        "${DEPLOY_DIR}/${DESIGN_NAME}.xsa"
    puts "INFO: XSA exported. Extract HWH from XSA manually if needed:"
    puts "      unzip ${DESIGN_NAME}.xsa ${DESIGN_NAME}.hwh"
}

# ── Step 3: Export XSA for PetaLinux 2020.1 ─────────────────
# PetaLinux 2020.1 uses .xsa (replaces older .hdf format from 2019.x)
puts "INFO: Exporting XSA for PetaLinux 2020.1..."
write_hw_platform \
    -fixed \
    -force \
    -include_bit \
    "${DEPLOY_DIR}/${DESIGN_NAME}.xsa"
puts "INFO: XSA exported to ${DEPLOY_DIR}/${DESIGN_NAME}.xsa"

# ── Step 4: Timing Summary ───────────────────────────────────
puts "\nINFO: Reading timing summary..."
set timing_rpt [report_timing_summary \
    -return_string \
    -check_timing_verbose \
    -delay_type max \
    -max_paths 1 \
    -quiet]

# Extract WNS (Worst Negative Slack)
if {[regexp {Worst Negative Slack \(WNS\)\s*:\s*(-?\d+\.\d+)} \
        $timing_rpt match wns]} {
    puts "INFO: Worst Negative Slack (WNS): ${wns} ns"
    if {$wns >= 0} {
        puts "INFO: ✓ Timing PASSED"
    } else {
        puts "WARN: ✗ Timing FAILED (WNS = ${wns} ns)"
        puts "      Consider relaxing clock or using Performance_ExplorePostRoutePhysOpt strategy"
    }
}

# ── Step 5: Utilisation Summary ─────────────────────────────
puts "\nINFO: Post-Implementation Resource Utilisation:"
report_utilization -quiet -return_string

# ── Step 6: Generate Deployment Package ─────────────────────
puts "\nINFO: Creating deployment README..."
set fp [open "${DEPLOY_DIR}/DEPLOY_README.txt" w]
puts $fp "EdgeAI-ZU4EV Deployment Package"
puts $fp "================================"
puts $fp "Generated by Vivado 2020.1"
puts $fp ""
puts $fp "Files:"
puts $fp "  ${DESIGN_NAME}.bit   — FPGA bitstream (load with PYNQ Overlay)"
puts $fp "  ${DESIGN_NAME}.hwh   — Hardware Hand-off (PYNQ IP descriptor)"
puts $fp "  ${DESIGN_NAME}.xsa   — Xilinx Support Archive (PetaLinux BSP)"
puts $fp ""
puts $fp "Board deployment:"
puts $fp "  1. Boot ALINX ACU4EV with PetaLinux 2020.1 or PYNQ 2.6 image"
puts $fp "  2. Copy .bit and .hwh to /home/root/ on the board:"
puts $fp "       scp ${DESIGN_NAME}.bit ${DESIGN_NAME}.hwh root@<board_ip>:/home/root/"
puts $fp "  3. Run inference notebook: deployment/board_deployment.ipynb"
puts $fp ""
puts $fp "PetaLinux BSP rebuild (if needed):"
puts $fp "  petalinux-create -t project -n edgeai_bsp"
puts $fp "  petalinux-config --get-hw-description=${DESIGN_NAME}.xsa"
puts $fp "  petalinux-build"
puts $fp "  petalinux-package --boot --u-boot --fpga ${DESIGN_NAME}.bit --force"
close $fp

puts ""
puts "================================================================"
puts "  Export Complete!"
puts "  Deploy directory: [file normalize ${DEPLOY_DIR}]"
puts ""
foreach f [glob -nocomplain "${DEPLOY_DIR}/*"] {
    set sz [file size $f]
    puts "  [file tail $f]  ([format %.1f [expr {$sz/1024.0/1024.0}]] MB)"
}
puts "================================================================"
